---
- name: Part 1 - Provision Core Container Dependencies on All Nodes
  hosts: master, workers
  become: yes
  roles:
    - common

- name: Part 2 - Configure Control Plane Cluster Topology
  hosts: master
  become: yes
  roles:
    - k8s-master

- name: Part 3 - Register Workers to Cluster Network
  hosts: workers
  become: yes
  roles:
    - k8s-worker